# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12eUCcNqHA6rHPszuyigs9ymjBpOSBcaQ
"""

# 讀取輸入並以空格切割成列表
scores = input().split()

# 初始化不及格計數器
fail_count = 0

# 遍歷所有成績
for s in scores:
    # 將字串轉換為整數進行比較
    if int(s) < 60:
        fail_count += 1

# 輸出結果
print(fail_count)