# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKoeFMuP831e0GhZ3L-r7U3R-3V20AXv
"""

# 讀取輸入並以空格切割成列表
scores = input().split()

# 將所有成績轉成整數
scores = [int(s) for s in scores]

# 計算平均數
average = sum(scores) / len(scores)

# 計算不及格數量
fail_count = 0
for s in scores:
    if s < 60:
        fail_count += 1

# 輸出平均數
print(average)

# 輸出不及格數量
print(fail_count)

# 輸出最大值與最小值
print(max(scores))
print(min(scores))
